name: OWASP ZAP Integration with Github Action
on: 
 push:
  branches: [ "master" ]
 pull_request: 
  branches: [ "master" ]
 workflow_dispatch:
 
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
  # full active scan before reporting the results, https://github.com/marketplace/actions/owasp-zap-full-scan   
        uses: zaproxy/action-full-scan@v0.8.0
  # The passive scanning to complete before reporting the results https://github.com/marketplace/actions/owasp-zap-baseline-scan
      #  uses: zaproxy/action-baseline@v0.8.2         
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://uat-healthhub-patient-api.azurewebsites.net/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
